[package]
name = "midirave"
version = "0.1.0"
edition = "2024"

[dependencies]
rustysynth = { git = "https://github.com/wsand02/rustysynth.git", branch = "breakallthethings", version = "1.3.6" }
hound = "3.5.1"
clap = { version = "4.5.56", features = ["derive"] }
anyhow = "1.0"
